#!/usr/bin/env bash
#
# Ships the i18n work. Run once from the repo root, then delete this file
# (the last line does it for you).
#
#   bash ship.sh
#
# Written as a script because the assistant's sandbox can create files under
# .git but cannot unlink them, so git could never release its own index.lock.
set -euo pipefail

cd "$(dirname "$0")"

# Left behind by the failed commit attempt. Nothing is running; the lock is
# stale, and git refuses to touch the index until it is gone.
rm -f .git/index.lock .git/_probe
rm -f .git/objects/*/tmp_obj_* 2>/dev/null || true

# Generated by a build, not by the i18n work. Keep it off both commits.
git checkout -- next-env.d.ts 2>/dev/null || true

echo "==> commit 1/2: licensing"
git add LICENSE CLA.md README.md README.zh-CN.md package.json
git commit -F - <<'MSG'
chore: dual-license the project under AGPL-3.0 with a CLA

Running a modified copy as a closed network service is the failure mode this
project is exposed to, so AGPL rather than GPL: section 13 is the clause that
reaches a hosted fork at all.

Dual licensing is what the CLA is for. Without contributors assigning the
rights, a commercial licence could not be offered over code the project does
not wholly own, and the AGPL obligation would be the only terms available.

Both READMEs say the same thing in their own language, and package.json now
declares the licence so tooling reads it without parsing prose.
MSG

echo "==> commit 2/2: i18n"
git add -A
git commit -F - <<'MSG'
feat: speak Simplified Chinese and English

Three separate layers were tangled together as one hard-coded language, and
they are separated here rather than translated in place.

Interface copy moves to src/lib/i18n. zh-CN is the reference dictionary and
defines the type, so a key added there and forgotten in en fails the type
check instead of rendering blank. Only the locale crosses the server/client
boundary — several entries are functions, which cannot be serialised into an
RSC payload, and shipping the copy twice would be wasteful even if they could.

Language is a cookie, not a path segment. A /play/[slug] link is shared as-is
and has to keep resolving for whoever opens it. The proxy negotiates from
Accept-Language on the first request and writes the request's own cookie jar in
the same pass, so the first page anyone sees is already in the right language
rather than the second.

API routes now answer with a code, never a sentence. A detached generation run
has no request to read a cookie from, and the reader's language is a fact only
the client holds. Failures record the code in metadata.errorCode; rows written
before that column existed still hold prose, which the lookup passes through as
unrecognised rather than crashing on. Build, workspace and validation
diagnostics became English instead: they surface in the console pane beside
esbuild's own output, where a mixed-language log is harder to read, not easier.

Generated games follow what the user typed, not the interface language —
someone reading English who writes a Chinese prompt wants a Chinese game. The
prompts say so explicitly, and say to judge it from the user's own words rather
than from anything else in the context. Title normalisation grew an English
path: leading verbs and articles stripped on word boundaries, so "Makeshift"
keeps its first syllable, and a wider cap because that alphabet needs the room.

SPEC.md keeps English scaffolding with content in the user's language. The
changelog is recovered by matching its heading, so a translated heading would
be a different anchor and switching language would silently drop a project's
entire history. The old Chinese heading stays in the match list for projects
that already carry it.

A prompt field pre-filled with an example follows a language switch only while
it still holds an example. Its value outlives the server re-render the switch
triggers, so without this the box keeps the language the page was opened in;
resetting unconditionally would be the worse bug, throwing away a half-written
prompt. Tests pin that the two locales never share a seed, since if they did
the whole failure would be invisible.

The switcher is an icon button with a menu. Language is set once and never
touched again, so it does not deserve standing space in the header, and it sits
last there: it is settings, not navigation. The display name follows the same
reasoning — a pencil, not a field standing permanently open — and a failed save
stays in edit mode, because dropping back to read mode would look like it
worked.
MSG

echo
git log --oneline -3
echo
echo "==> pushing to main"
git push origin main

rm -- "$0"
